---

name: update-flake-lock

on:
  workflow_dispatch:  # allows manual triggering
  schedule:
    - cron: '0 5,17,21 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/update-flake-lock@v24
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          nix-options: --debug --log-format raw
          pr-title: "Update flake.lock"  # Title of PR to be created
          pr-labels: |                   # Labels to be set on the PR
            dependencies
            automated
